name: Publish image in Docker Hub

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: docker build --build-arg VERSION_TAG=${{ github.event.release.tag_name }} -t alevarmun1us/natillas-hub:${{ github.event.release.tag_name }} -f docker/images/Dockerfile.prod .
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled

      - name: Push Docker image to Docker Hub
        run: docker push alevarmun1us/natillas-hub${{ github.event.release.tag_name }}

      - name: Tag and push latest
        run: |
          docker tag alevarmun1us/natillas-hub${{ github.event.release.tag_name }} alevarmun1us/natillas-hub:latest
          docker push alevarmun1us/natillas-hub:latest
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
